apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mlflow-artifact-connection"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["mlflow.kubeflow.org"]
    resources: ["mlflowconfigs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mlflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mlflow.fullname" . }}
    namespace: {{ include "mlflow.namespace" . }}
{{- if .Values.traceArchival.enabled }}
  - kind: ServiceAccount
    name: {{ include "mlflow.traceArchival.fullname" . }}
    namespace: {{ include "mlflow.namespace" . }}
{{- end }}
{{- if .Values.garbageCollection.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mlflow.gc.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: gc
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mlflow-artifact-connection"]
    verbs: ["list", "watch"]
  - apiGroups: ["mlflow.kubeflow.org"]
    resources: ["mlflowconfigs"]
    verbs: ["list", "watch"]
  - apiGroups: ["mlflow.kubeflow.org"]
    resources: ["experiments"]
    verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mlflow.gc.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mlflow.gc.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mlflow.gc.fullname" . }}
    namespace: {{ include "mlflow.namespace" . }}
{{- end }}
