apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ include "mlflow.namespace" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- if .Values.garbageCollection.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.gc.fullname" . }}
  namespace: {{ include "mlflow.namespace" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: gc
automountServiceAccountToken: false
{{- end }}
{{- if .Values.traceArchival.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.traceArchival.fullname" . }}
  namespace: {{ include "mlflow.namespace" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: trace-archival
automountServiceAccountToken: false
{{- end }}
