{{- if and .Values.istio.enabled .Values.istio.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ include "mlflow.namespace" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  action: {{ .Values.istio.authorizationPolicy.action | default "ALLOW" }}
  selector:
    matchLabels:
      {{- include "mlflow.serverSelectorLabels" . | nindent 6 }}
  {{- with .Values.istio.authorizationPolicy.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
